8GeV config added for inclusive sample
LDMXAnalysis/ldmx-sw pull request #1272
Opened 2024-03-20 22:03 UTC by pritampalit

I am updating _ldmx-sw_, here are the details.

## Check List
- [ ] I successfully compiled _ldmx-sw_ with my developments

- [ ] I ran my developments and the following shows that they are successful.

Link to [presentation](https://indico.fnal.gov/event/63853/#6-8-gev-inclusive-sample-valid)

- [ ] I attached any sub-module related changes to this PR.

To run this config : 
```
ldmx fire .github/validation_samples/inclusive/config_inclusive_8gev.py [run_number] [max_events] [max_TriesPerEvent]
```

2024-03-21 14:51 UTC, bryngemark reviewed
I think we don't want a new file called `..._8gev`but actually an update to the existing file. 8 GeV is our new default and this should be reflected in our CI configs. Changing the original file also makes it easier to review your exact changes in the pull request.

2024-03-21 14:53 UTC, bryngemark commented
by the way i expect the associated test to break if you rename the existing file, since two different beam energies are compared. that is ok. it would be good to just take a quick look at the resulting histograms ("artifacts") that the diffrences are expected, just as you have done for validation.

2024-03-27 13:25 UTC, tomeichlersmith requested changes
Besides a niche output-filename change that is required for the CI, I can't think of anything else to change. As @bryngemark said, this will fail the PR Validation histograms but those histograms will be interesting to look at.

2024-03-27 13:25 UTC, tomeichlersmith commented on .github/validation_samples/inclusive/config.py
> +p.outputFiles = ['events_8gev.root']
The output histogram and event files should keep the same names as before so that they are picked up by the CI.

```suggestion
p.histogramFile = 'hist.root'
p.outputFiles = ['events.root']
```

2024-03-27 16:27 UTC, pritampalit commented on .github/validation_samples/inclusive/config.py
> +p.outputFiles = ['events_8gev.root']
I changed the output file name, because probably the validation tool takes a key_val pair as the file name. I have again changed it to default one.

2024-03-27 16:37 UTC, tomeichlersmith commented on .github/validation_samples/inclusive/config.py
> +p.outputFiles = ['events_8gev.root']
That makes sense, the CI script pre-dates the Validation tool and we are hoping to unify them one day.

2024-03-30 14:46 UTC, bryngemark approved these changes

2024-04-09 15:46 UTC, tvami approved these changes

2024-04-09 15:47 UTC, tvami commented
I think this needs to go in before we change the CI configs to add the debug level info as discussed in https://github.com/LDMX-Software/ldmx-sw/pull/1277#issuecomment-2045344641

2024-04-10 14:26 UTC, tomeichlersmith approved these changes

2024-04-10 14:26 UTC, merged