Introduce DeepEcalProcessFilter
LDMXAnalysis/ldmx-sw pull request #1289
Opened 2024-04-27 16:20 UTC by tvami

I am updating _ldmx-sw_, here are the details.

### What are the issues that this addresses?
Resolves https://github.com/LDMX-Software/ldmx-sw/issues/1288

## Check List
- [x] I successfully compiled _ldmx-sw_ with my developments
- [x] I ran my developments and the following shows that they are successful.

Produced events with the depth of 400:
```
Started 2962289 events to produce 10000 events.
```

@tylerhoroho-UVA is testings them now

- [x] I attached any sub-module related changes to this PR.

N/A

2024-05-03 02:08 UTC, tvami commented
As a validation I ran the config at 400, the hard brem seem to stop there and that's where the daughters are starting: 
<img width="395" alt="Screenshot 2024-05-02 at 19 04 53" src="https://github.com/LDMX-Software/ldmx-sw/assets/5064110/5e2ff787-fa40-44c9-9ac3-172a3869e930">

@tylerhoroho-UVA I put the file that contains 276 events (I meant to have 1000, but from 10000000 tries it could only go upto 276 events [also meaning that the z=500 will take a long time to produce stats])
```
/u/gu/tamasvami/events_pn_deep_test_276events.root
```

2024-05-03 22:29 UTC, tvami commented
In https://github.com/LDMX-Software/ldmx-sw/pull/1289/commits/24f9e0ba0a0b7a15b4ca80ae642c25c9a8447974?diff=split&w=1 I updated the DQM plots to show the particle types, now it looks like this:
<img width="460" alt="Screenshot 2024-05-03 at 15 25 26" src="https://github.com/LDMX-Software/ldmx-sw/assets/5064110/fae5b5b0-2234-4cef-a7be-d3b01d0e0af9">

2024-05-07 00:22 UTC, tvami commented
OK I'm done with the filter that doesnt require the photon to come from the target.
The changes for the file size: the brem photon is tagged, no other brem is saved; tagging the relevant conversion vs saving all conversion has a ~15% increase in size (152KB vs 130KB per event) so I am more comfortable to save all of them, this makes the code easier to read anyway (I can say more if needed why the code gets complicated otherwise) and makes sure we dont miss any of the relevant physics.

Tyler in the meanwhile is taking an event from my event.root and resimulates it with the target filter on to see what's happening. We may want to have that part decoupled from this PR, although we are not in a rush.

2024-05-07 20:02 UTC, tvami commented
OK in the last push I introduced `require_photon_fromTarget_` that governs if we want to force the photon to come from the target. Worked nicely on one event, I'll make a bit more and then move the PR to "ready to review"

2024-05-19 14:19 UTC, tvami commented
Interesting, the `volume.contains("target")` actually brings in much more than just the target. 
<img width="346" alt="Screenshot 2024-05-19 at 09 13 53" src="https://github.com/LDMX-Software/ldmx-sw/assets/5064110/d3855744-05bf-4532-b685-29856c7258cc">

@tylerhoroho-UVA I assume this is not good. Maybe we could enforce instead that it's coming from around Z=0 instead of going thru the volume definition. Alternatively if these are called `targetTS` or something like that I could enforce that it should be target but not any TS related. But since the target will always be at Z=0(ish) I think that's a less involved solution. What do you think?

2024-05-20 14:43 UTC, tylerhoroho-UVA commented
Interesting. From looking at the .gdml files I don't see any objects (other than the target) that contain a `"target"` substring in their volume name. Maybe it's something on the G4 level that's assigning the name?
If z values can be used instead of substrings in volumes, I think -0.5 < z < 0.5 would fully contain everything in the target plus a little extra room.

2024-05-20 15:34 UTC, tvami commented
Yes, I think everything the the target.gdml, i.e. these https://github.com/LDMX-Software/ldmx-sw/blob/trunk/Detectors/data/ldmx-det-v14-8gev/target.gdml#L72-L91 are going to be called target by G4. 

OK, let's do it with the `-0.5 < z < 0.5`, I'll push the commit when I have it

2024-05-31 23:36 UTC, tvami commented
Talked to Tyler about the issue above, and we concluded that it's better to keep this as it is (in real data we wont know if the interaction happened on the TS or the target), and we can always just remove these at the analysis level. It's also a small effect

2024-06-01 00:02 UTC, tylerhoroho-UVA approved these changes

2024-06-03 14:44 UTC, tomeichlersmith requested changes
I have some suggested refactors hoping to insure ourselves against future confusion. Mainly moving variable declarations, definitions, and usage "close" to each other in the code.

## Larger Comment
This filter makes the decision on whether to abort an event within `NewStage` which makes sense and allows for the simulation to avoid costly shower simulations that are unneeded. Nevertheless, this choice ties the filter closely to the PartialEnergySorter. I would encourage you to survey values of the biasing threshold and the sorting threshold to see how high you can raise it before losing access to the events you want to study. Generally, the higher the thresholds are, the less of the shower the simulation needs to do before it has the opportunity to abort the event.

2024-06-03 14:44 UTC, tomeichlersmith commented on DQM/include/DQM/SampleValidation.h
> +
```suggestion
```

2024-06-03 14:44 UTC, tomeichlersmith commented on Biasing/test/resim_ecal_conv_deep.py
> +mysim = ecal.deep_photo_nuclear(det, generators.single_8gev_e_upstream_tagger(), bias_threshold = 3000., processes=['conv','phot)'], ecal_min_Z = 400.)
This definition of a simulator does not match the one in the original simulation which can lead to funky results when re-simulating. Maybe just add a comment explaining that the user should align these two?

2024-06-03 14:44 UTC, tomeichlersmith commented on Biasing/src/Biasing/DeepEcalProcessFilter.cxx
> +bool hasDeepEcalProcess_{false};
```suggestion
```

2024-06-03 14:44 UTC, tomeichlersmith commented on Biasing/include/Biasing/DeepEcalProcessFilter.h
> +
```suggestion
  /// member used to help tag events where the photon comes from the target
  bool photonFromTarget_{false};
  /// member used to help tag events that have a deep-ecal process ocurr
  bool hasDeepEcalProcess_{false};
```

2024-06-03 14:44 UTC, tomeichlersmith commented on Biasing/src/Biasing/DeepEcalProcessFilter.cxx
> +
```suggestion
```

2024-06-03 14:44 UTC, tomeichlersmith commented on Biasing/src/Biasing/DeepEcalProcessFilter.cxx
> +  // Tag if the event has the processes we are looking for
```suggestion
  // Tag if the event has the processes we are looking for
  bool hasProcessNeeded{false};
```

2024-06-03 14:44 UTC, tomeichlersmith commented on Biasing/src/Biasing/DeepEcalProcessFilter.cxx
> +      hasProcessNeeded_ = true;
```suggestion
      hasProcessNeeded = true;
```

2024-06-03 14:44 UTC, tomeichlersmith commented on Biasing/src/Biasing/DeepEcalProcessFilter.cxx
> +
```suggestion
  // skip this step if it does not have any of the processes needed
  if (not hasProcessNeeded) return;

```

The goal in moving this check earlier is two fold:
1. Keep a value's definition and usage close together so folks can see how it is used.
2. Avoid costly string comparisons below if they aren't needed.

2024-06-03 14:44 UTC, tomeichlersmith commented on Biasing/src/Biasing/DeepEcalProcessFilter.cxx
> +  if (!hasProcessNeeded_ or !isInEcal) return;
```suggestion
  if (not isInEcal) return;
```

2024-06-03 17:01 UTC, tvami commented on Biasing/test/resim_ecal_conv_deep.py
> +#mysim = ecal.deep_photo_nuclear(det, generators.single_8gev_e_upstream_tagger(), bias_threshold = 5010., processes=['conv','phot)'], ecal_min_Z = 300.)
```suggestion
# Please make sure that the simulator here matches the simulator in the original config
#mysim = ecal.deep_photo_nuclear(det, generators.single_8gev_e_upstream_tagger(), bias_threshold = 5010., processes=['conv','phot)'], ecal_min_Z = 300.)
```

2024-06-03 17:10 UTC, tomeichlersmith approved these changes

2024-06-03 17:17 UTC, tvami commented
> I would encourage you to survey values of the biasing threshold and the sorting threshold to see how high you can raise it before losing access to the events you want to study. 

Maybe this could be a good study for Anmol, what do you think @tylerhoroho-UVA ?
(This certainly can be done after the PR is merged since it's configuration variable)

I ran the test file again after the changes (with a start Z of 240 mm), the DQM histograms look good
<img width="354" alt="Screenshot 2024-06-03 at 10 17 29" src="https://github.com/LDMX-Software/ldmx-sw/assets/5064110/aeddd811-7134-43a5-a619-5d0089b6e7c8">

2024-06-03 17:26 UTC, merged