Introduce variable for total events with no tries limit
LDMXAnalysis/ldmx-sw pull request #1322
Opened 2024-05-06 21:57 UTC by tvami

I am updating _ldmx-sw_, here are the details.

### What are the issues that this addresses?
This resolves https://github.com/LDMX-Software/ldmx-sw/issues/1299

## Check List
- [x] I successfully compiled _ldmx-sw_ with my developments
- [x] I ran my developments and the following shows that they are successful.

I ran the pn code and set 
```
p.run = 2
p.maxEvents = 1
```
 * In default I get
```
Started 23 events to produce 1 events.
```

 * then
```
p.maxEvents = 1
p.maxTriesPerEvent = 10
```
leads to
```
Started 10 events to produce 1 events.
```

 * then
```
p.maxEvents = 1
p.maxTriesPerEvent = 10
p.totalEvents = 1
```
leads again to 
```
[ Process ] 2 : The totalEvents was set, so maxEvents and maxTriesPerEvent will be ignored!
Started 23 events to produce 1 events.
```
as expected

2024-05-06 22:23 UTC, tomeichlersmith requested changes
This looks good, I would just ask for the `totalEvents` config option to be added to the python config class documentation and include reference to it in the `max*` descriptions since they will be ignored if it is used.

https://github.com/LDMX-Software/ldmx-sw/blob/11d6a8e89250b357885602075c88b423dc04cdeb/Framework/python/ldmxcfg.py.in#L330-L334

2024-05-06 22:23 UTC, tomeichlersmith commented on Framework/src/Framework/Process.cxx
> +    // starting at line 240 of Process.cxx on trunk
```suggestion
```

2024-05-07 00:04 UTC, tvami commented
Thanks Tom, I've changed those points

2024-05-07 02:05 UTC, tomeichlersmith approved these changes

2024-05-07 03:32 UTC, danyi211 approved these changes

2024-05-07 12:27 UTC, tylerhoroho-UVA approved these changes

2024-05-07 14:09 UTC, merged