Make all truth tracking collections even with 0 SimHits
LDMXAnalysis/ldmx-sw pull request #1372
Opened 2024-07-09 19:02 UTC by bloodyyugo

I've modified TruthSeedProcessor so that it no longer skips MC events with 0 SimHits in either recoil or tracker collections (issue 1371).  This caused a crash downstream when one of the truth collections was (attempted) to be used.  

In the update, an error-level message will be printed when it encounters an empty SimHits collection but (empty) truth seed and track collections will be made.  

The error messages can be turned off (for instance if the tagger wasn't simulated) by setting the new config variable skip_XXXX to true, for example:   
`truth_tracking.skip_tagger       = True`
a 'skip_recoil' variable exists as well.  Note that these also turn off the relevant truth-track-making code as well.  These config variables are set to 'False' by default. 

I've also changed some log entries from 'info' to 'debug' level.

2024-07-09 19:17 UTC, tomeichlersmith requested changes
- The clang-format check is failing, please format the source files you've changed.[^1]
- Please put the new parameters into the [associated python config class](https://github.com/LDMX-Software/ldmx-sw/blob/8b4650fea34453bd12ccfb7dc03a3645f8616877/Tracking/python/tracking.py#L241-L297). While this isn't necessary (as you've discovered), it is helpful for discoverability of the available run-time parameters.

[^1]: This program is available within the container so you can run `ldmx clang-format -i Tracking/include/Tracking/Reco/TruthSeedProcessor.h Tracking/src/Tracking/Reco/TruthSeedProcessor.cxx` in order to do the formatting. Please let me know if this doesn't work so I don't keep telling people the wrong thing.

2024-07-09 20:33 UTC, bloodyyugo commented
Ok, I've fixed the formatting and added the variables to tracking.py.  It looks like tracking.py needs some other updating, but I'll add that to my list.

2024-07-09 20:35 UTC, tomeichlersmith commented
Yea, it looks like you ran the clang-format over the python file. This generally mangles the results unfortunately.

2024-07-09 23:21 UTC, bloodyyugo commented
> Yea, it looks like you ran the clang-format over the python file. This generally mangles the results unfortunately.

Damn it.   I fixed this up

2024-07-09 23:38 UTC, sophiemiddleton approved these changes
this looks good, thanks for looking at this

2024-07-10 14:00 UTC, tomeichlersmith approved these changes
Looking good, thanks for cleaning things up!

2024-07-10 14:00 UTC, tomeichlersmith commented on Tracking/src/Tracking/Reco/TruthSeedProcessor.cxx
> +  // In tracking frame:  MG where do these numbers come from?
These numbers come from an approximation of where the beam generator places the beam (without smearing) just upstream of all detector components. `-880.1` is just upstream of TriggerPad1 in `z` and `-44` is approximately the bend in `x` imposed on the beam by the magnet (I think 4GeV but could be 8GeV). Then they are re-ordered to be in tracking coordinates.

2024-07-10 16:19 UTC, merged