Introduction of SegMIP BDT + other improvement on ECAL veto
LDMXAnalysis/ldmx-sw pull request #1383
Opened 2024-08-09 23:53 UTC by tvami

I am updating _ldmx-sw_, here are the details.

### What are the issues that this addresses?

Resolves https://github.com/LDMX-Software/ldmx-sw/issues/1287
Resolves https://github.com/LDMX-Software/ldmx-sw/issues/1305

We have shown the results of the software changes already at a SWAN meeting. The latest BDT that's now trained on the full E14 trigger skimmed data is included now too. This is to be shown at a SWAN meeting. 

Future improvements in another PR will include factorizing the MIP tracking out of this class. 

## Check List
- [x] I successfully compiled _ldmx-sw_ with my developments
- [x] I ran my developments and the following shows that they are successful.

2024-08-09 23:55 UTC, tvami commented
We expect the tests to fail, both logs and histogram comparisons.

2024-08-10 00:25 UTC, tvami commented
> Error in <TFile::TFile>: file hist.root does not exist

this should be not related

2024-08-10 00:26 UTC, tvami commented
Nvm, the issue is in the prev line

> ERROR: ONNX model file '/home/runner/work/ldmx-sw/ldmx-sw/install/data/Ecal/segmip.onnx' does not exist.

Let me fix this typo

2024-08-11 20:07 UTC, tvami commented
Lots of diffs in the validation, many actually come from a simple change that now the electron beam energy in the ecal veto is configurable, now the plots are correct (meaning consistent) for the signal. For the ecal pn, we need to change the config to be at 8 GeV. I also think we should run tracking in the validation configs. I can do that in another PR. 

I propose to do that next and have new golds / subversion change after that so then we can launch a BDT skim.

2024-08-12 15:04 UTC, tomeichlersmith requested changes
As usual, I mainly have some C++ technical comments. I think this implementation looks good and resolves two (:two: :exclamation: ) issues so I'm happy its going to be merged.

I will continue to grumble about https://github.com/LDMX-Software/ldmx-sw/issues/1306 but leave that for future work.

2024-08-12 15:04 UTC, tomeichlersmith commented on DQM/src/DQM/EcalMipTrackingFeatures.cxx
> +  auto veto{
This should be a `const` reference to avoid copying. While its not a big deal for the relatively small veto result, I want folks to get in the habit to avoid performance issues from e.g. copying the 100+ length vector of ecal hits on each event.

```suggestion
  const auto& veto{
```

2024-08-12 15:04 UTC, tomeichlersmith commented on Ecal/include/Ecal/Event/EcalVetoResult.h
>    /** px of recoil electron at the Ecal face. */
For some reason, GitHub doesn't allow me to add comments on un-changed code, but since you are modifying the event object you need to update its version so that ROOT will not :shit: itself[^1] when attempting to load files with the prior copy of veto result.

```cpp
  // at bottom of class declaration
  ClassDef(EcalVetoResult, 6); // 6 instead of 5
```

[^1]: I'm being overly dramatic due to my personal dislike of the library. Most of the time, it just issues some warnings to stderr that can be ignored by folks who aren't using the veto result.

2024-08-12 15:04 UTC, tomeichlersmith commented on Ecal/src/Ecal/EcalVetoProcessor.cxx
> -  bdtFeatures_.clear();
:eyes: we sure that this isn't expanding with each event? It is named and acting like a member variable and (as far as I can tell) is not `clear`ed anywhere.

Side Note: why is this a member variable at all? why not just have `buildBDTFeatureVector` _return_ the vector and then give that (local) vector to the function that inferences?

2024-08-12 16:20 UTC, tvami commented on Ecal/src/Ecal/EcalVetoProcessor.cxx
> -  bdtFeatures_.clear();
It's cleared here
https://github.com/LDMX-Software/ldmx-sw/blob/trunk/Ecal/src/Ecal/EcalVetoProcessor.cxx#L168

Yeah, let's come back to the member variable question in the PR where we break the veto up to several pieces.

2024-08-12 19:01 UTC, tvami commented on Ecal/include/Ecal/Event/EcalVetoResult.h
>    /** px of recoil electron at the Ecal face. */
done in the next commit

2024-08-12 19:02 UTC, tvami commented on DQM/src/DQM/EcalMipTrackingFeatures.cxx
> +  auto veto{
done in next commit

2024-08-12 19:21 UTC, tomeichlersmith commented on DQM/src/DQM/EcalMipTrackingFeatures.cxx
> +  auto recoil_mom = veto.getRecoilMomentum();
```
  /home/runner/work/ldmx-sw/ldmx-sw/DQM/src/DQM/EcalMipTrackingFeatures.cxx: In member function 'virtual void dqm::EcalMipTrackingFeatures::analyze(const framework::Event&)':
  /home/runner/work/ldmx-sw/ldmx-sw/DQM/src/DQM/EcalMipTrackingFeatures.cxx:24:43: error: passing 'const ldmx::EcalVetoResult' as 'this' argument discards qualifiers [-fpermissive]
     24 |   auto recoil_mom = veto.getRecoilMomentum();
        |                     ~~~~~~~~~~~~~~~~~~~~~~^~
  In file included from /home/runner/work/ldmx-sw/ldmx-sw/DQM/src/DQM/EcalMipTrackingFeatures.cxx:4:
  /home/runner/work/ldmx-sw/ldmx-sw/Ecal/include/Ecal/Event/EcalVetoResult.h:213:23: note:   in call to 'std::vector<double> ldmx::EcalVetoResult::getRecoilMomentum()'
    213 |   std::vector<double> getRecoilMomentum() {
        |                       ^~~~~~~~~~~~~~~~~
  make[2]: *** [DQM/CMakeFiles/DQM.dir/build.make:104: DQM/CMakeFiles/DQM.dir/src/DQM/EcalMipTrackingFeatures.cxx.o] Error 1
```

:fist_right: :cloud: (shaking fist at sky)

I guess since we are already modifying EcalVetoResult we can improve its `const`-correctness. :shrug:

2024-08-12 20:13 UTC, tvami commented on DQM/src/DQM/EcalMipTrackingFeatures.cxx
> +  auto recoil_mom = veto.getRecoilMomentum();
done

2024-08-12 21:00 UTC, tomeichlersmith approved these changes

2024-08-12 21:57 UTC, danyi211 approved these changes

2024-08-12 23:15 UTC, merged