Update tracking to use Acts v36.0
LDMXAnalysis/ldmx-sw pull request #1454
Opened 2024-09-13 23:19 UTC by bloodyyugo

Pull request [addresses issue 1356](https://github.com/LDMX-Software/ldmx-sw/issues/1365), upgrading tracking to use ACTs version 36.0.  
 
The development branch is actsv36.0 and compiles, builds and runs. Comparisons between tracking using the previous ACTs version (19.X ... something) are shown on the issue page linked above.  

There is one outstanding problem in that we see fewer hits-on-track for tagger tracks with this update.  We don't see this in the recoil for some reason.  We are investigating but this issue can be closed without it.

2024-09-13 23:34 UTC, tvami commented
hey @bloodyyugo we'll have to rebase this due to the fact that my other PR was touching on the same files

2024-09-13 23:35 UTC, bloodyyugo commented
Yeah, I'll redo now.

2024-09-14 04:12 UTC, tvami requested changes
First of all, thanks a lot Matt for doing this update, I think it's very important for the collaboration. I have a range of comments, starting from cosmetics, to changes that are needed for our planned compiler change, to the point of the constructor of `Linearizer::Config` stuff (this last one seems pretty important, the rest if you want I can take care of myself too, just let me know)

2024-09-14 04:12 UTC, tvami commented on Tracking/include/Tracking/Reco/DigitizationProcessor.h
> +//#include "Acts/Digitization/PlanarModuleStepper.hpp"
Do you think these might be needed in the future? If not might be cleaner to delete them for good
```suggestion
```

2024-09-14 04:12 UTC, tvami commented on Tracking/include/Tracking/Reco/GSFProcessor.h
> +//#include "Acts/EventData/detail/TransformationFreeToBound.hpp"
if it's not in v36 I think we should remove it
```suggestion
```

2024-09-14 04:12 UTC, tvami commented on Tracking/include/Tracking/Reco/TruthSeedProcessor.h
> +//#include "Acts/EventData/detail/TransformationFreeToBound.hpp"
```suggestion
```

2024-09-14 04:12 UTC, tvami commented on Tracking/include/Tracking/Sim/MeasurementCalibrator.h
> +        local_cov;  // make tsCalCov 2x2 block the local_cov we just set
```suggestion
     // make tsCalCov 2x2 block the local_cov we just set
    tsCalCov.block(0, 0, 2, 2) = local_cov; 
```
clang like to have the comment a line above

2024-09-14 04:12 UTC, tvami commented on Tracking/python/tracking.py
> +        self.debug = True
```suggestion
        self.debug = False
```
should we have the default on False?

2024-09-14 04:12 UTC, tvami commented on Tracking/src/Tracking/Reco/CKFProcessor.cxx
> +      //        propagator_options.mass = 938 * Acts::UnitConstants::MeV;
I dont see this ever needed again, right?
```suggestion
```

2024-09-14 04:12 UTC, tvami commented on Tracking/src/Tracking/Reco/CKFProcessor.cxx
> +    // if (tc.size() < trackId + 1) continue;
Should we have this a little bit more louder? Like a ldmx_log(warn) msg?

2024-09-14 04:12 UTC, tvami commented on Tracking/src/Tracking/Reco/SeedFinderProcessor.cxx
> +  strategy = {9,10,11,12,13};
Can you maybe add a comment above this regarding what these numbers mean?

2024-09-14 04:12 UTC, tvami commented on Tracking/src/Tracking/Reco/SeedFinderProcessor.cxx
> +      0.75 * p * Acts::UnitConstants::GeV;  // sigma set to 75% of momentum
again just to undo the clang's formatting 
```suggestion
  // sigma set to 75% of momentum
  double sigma_p = 0.75 * p * Acts::UnitConstants::GeV; 
```

2024-09-14 04:12 UTC, tvami commented on Tracking/include/Tracking/Reco/TrackExtrapolatorTool.h
>      bool boundaryCheck = false;
this will make clang complain, as it's unused in the current state
```suggestion
    // bool boundaryCheck = false;
```

2024-09-14 04:12 UTC, tvami commented on Tracking/include/Tracking/Reco/TrackExtrapolatorTool.h
> +    size_t nstates = track.nTrackStates();
Unused here, L175 has it again
```suggestion
```

2024-09-14 04:12 UTC, tvami commented on Tracking/include/Tracking/Reco/TrackExtrapolatorTool.h
> +                                           : -1 * Acts::UnitConstants::e;
the code that used this is commented out
```suggestion
/*
    Acts::ActsScalar q;
    if (hasSmoothed)
      q = smoothed[Acts::eBoundQOverP] > 0 ? 1 * Acts::UnitConstants::e
                                           : -1 * Acts::UnitConstants::e;
    else
      q = filtered[Acts::eBoundQOverP] > 0 ? 1 * Acts::UnitConstants::e
                                           : -1 * Acts::UnitConstants::e;
*/
```

2024-09-14 04:12 UTC, tvami commented on Tracking/include/Tracking/Reco/TrackExtrapolatorTool.h
> +    size_t nstates = track.nTrackStates();
```suggestion
```

2024-09-14 04:12 UTC, tvami commented on Tracking/include/Tracking/Reco/TrackExtrapolatorTool.h
>                               : -1 * Acts::UnitConstants::e;
Unused
```suggestion
    // Acts::ActsScalar q = smoothed[Acts::eBoundQOverP] > 0
    //                          ? 1 * Acts::UnitConstants::e
    //                          : -1 * Acts::UnitConstants::e;
```

2024-09-14 04:12 UTC, tvami commented on Tracking/src/Tracking/Reco/Vertexer.cxx
>    Linearizer::Config linearizerConfig(bField_, propagator_);
It seems there is no constructor with this form. Instead 
```suggestion
  Linearizer::Config linearizerConfig;
  linearizerConfig.bField = bField_;
  linearizerConfig.propagator = propagator_;
```
I see an example here like this
https://github.com/acts-project/acts/blob/main/Examples/Algorithms/Vertexing/src/VertexFitterAlgorithm.cpp#L58-L62

2024-09-14 04:12 UTC, tvami commented on Tracking/src/Tracking/Reco/VertexProcessor.cxx
>    Linearizer::Config linearizerConfig(sp_interpolated_bField_, propagator_);
Same comment as in Vertexer.cxx
```suggestion
  Linearizer::Config linearizerConfig;
  linearizerConfig.bField = sp_interpolated_bField_;
  linearizerConfig.propagator = propagator_;
```

2024-09-14 04:12 UTC, tvami commented on Tracking/src/Tracking/Reco/Vertexer.cxx
>    // Linearizer::Config linearizerConfig(sp_interpolated_bField_,propagator_);
```suggestion
```

2024-09-14 04:12 UTC, tvami commented on Tracking/src/Tracking/Reco/DigitizationProcessor.cxx
> +  // lAngle,
now that this is commented out, when running with CLANG
```
Tracking/src/Tracking/Reco/DigitizationProcessor.cxx:39:10: warning: unused variable 'lAngle' [-Wunused-variable]
  double lAngle = 0.01;
         ^
Tracking/src/Tracking/Reco/DigitizationProcessor.cxx:45:8: warning: unused variable 'isAnalog' [-Wunused-variable]
  bool isAnalog = true;
       ^
Tracking/src/Tracking/Reco/DigitizationProcessor.cxx:30:7: warning: unused variable 'nbinsx' [-Wunused-variable]
  int nbinsx = 128 * 5;
      ^
Tracking/src/Tracking/Reco/DigitizationProcessor.cxx:36:10: warning: unused variable 'thickness' [-Wunused-variable]
  double thickness = 0.320 * Acts::UnitConstants::mm;
         ^
Tracking/src/Tracking/Reco/DigitizationProcessor.cxx:42:10: warning: unused variable 'eThresh' [-Wunused-variable]
  double eThresh = 0.;
         ^
Tracking/src/Tracking/Reco/DigitizationProcessor.cxx:33:7: warning: unused variable 'nbinsy' [-Wunused-variable]
  int nbinsy = 1;
```

2024-09-14 04:12 UTC, tvami commented on Tracking/src/Tracking/Reco/GSFProcessor.cxx
> +      Acts::ComponentMergeMethod::eMaxWeight;
unused (well used in the commented code)
```suggestion
  // Acts::ComponentMergeMethod reductionMethod =
  // Acts::ComponentMergeMethod::eMaxWeight;
```

2024-09-14 04:12 UTC, tvami commented on Tracking/src/Tracking/Reco/CKFProcessor.cxx
>                                             : Acts::UnitConstants::e;
not used anymore
```suggestion
```

2024-09-14 04:12 UTC, tvami commented on Tracking/src/Tracking/Reco/CKFProcessor.cxx
>        int pdgID = seedPDGID.at(trackId);
```suggestion
      // int pdgID = seedPDGID.at(trackId);
```

2024-09-14 04:12 UTC, tvami commented on Tracking/src/Tracking/Reco/CKFProcessor.cxx
>        int pdgID = seedPDGID.at(trackId);
or delete if it's not expected to be used again

2024-09-14 04:12 UTC, tvami commented on Tracking/src/Tracking/Reco/CKFProcessor.cxx
> +        bool success = trk_extrap_->TrackStateAtSurface(
declaration shadows a local variable, prev declaration in L474

2024-09-14 04:12 UTC, tvami commented on Tracking/src/Tracking/Reco/CKFProcessor.cxx
> +      const Acts::BoundMatrix& trk_cov = track.covariance();
unused
```suggestion
      // const Acts::BoundMatrix& trk_cov = track.covariance();
```

2024-09-14 04:12 UTC, tvami commented on Tracking/src/Tracking/Reco/CKFProcessor.cxx
> +  auto extr_surface = &(*origin_surface);
unused
```suggestion
```

2024-09-14 04:12 UTC, tvami commented on Tracking/include/Tracking/Sim/MeasurementCalibrator.h
> +    auto tsIndexType = trackState.index();
```suggestion
```

2024-09-14 04:12 UTC, tvami commented on Tracking/include/Tracking/Sim/MeasurementCalibrator.h
> +    auto tsIndexType = trackState.index();
```suggestion
```

2024-09-14 04:12 UTC, tvami commented on Tracking/include/Tracking/Sim/MeasurementCalibrator.h
> +                    traj_t::TrackStateProxy trackState) const {
```suggestion
                   typename traj_t::TrackStateProxy trackState) const {
```

2024-09-14 04:12 UTC, tvami commented on Tracking/include/Tracking/Sim/MeasurementCalibrator.h
> +                 traj_t::TrackStateProxy trackState) const {
```suggestion
                typename traj_t::TrackStateProxy trackState) const {
```

2024-09-14 17:51 UTC, bloodyyugo commented on Tracking/src/Tracking/Reco/CKFProcessor.cxx
> +      //        propagator_options.mass = 938 * Acts::UnitConstants::MeV;
I'm actually not sure what this was used for in the first place.   Anyway, right now there is a lot of assumptions that these are all electrons/positrons.  It was somewhat less so before, but the way "boundTrackParameters" is built changed so I basically just went with electron assumption everywhere.  That will need to be fixed at somepoint.

2024-09-14 17:57 UTC, bloodyyugo commented on Tracking/src/Tracking/Reco/CKFProcessor.cxx
> +    // if (tc.size() < trackId + 1) continue;
I think this is ok for now.

2024-09-14 18:09 UTC, bloodyyugo commented on Tracking/src/Tracking/Reco/GSFProcessor.cxx
> +      Acts::ComponentMergeMethod::eMaxWeight;
Let's keep this as it's being actively developed.

2024-09-14 18:47 UTC, bloodyyugo commented on Tracking/src/Tracking/Reco/SeedFinderProcessor.cxx
> +  strategy = {9,10,11,12,13};
Added in next commit

2024-09-14 18:54 UTC, bloodyyugo commented on Tracking/src/Tracking/Reco/DigitizationProcessor.cxx
> +  // lAngle,
Git rid of all these and the commented out stuff.  In next commit.

2024-09-14 18:55 UTC, bloodyyugo commented on Tracking/src/Tracking/Reco/CKFProcessor.cxx
> +        bool success = trk_extrap_->TrackStateAtSurface(
Fixed in next commit.

2024-09-15 16:43 UTC, bloodyyugo commented
@tvami I think I resolved all of the issues

2024-09-15 17:58 UTC, tvami commented
Thanks Matt! I ran it on the ecal_pn + tracking config and I get the following error
```
Unrecognized Exception: vector::_M_range_check: __n (which is 16) >= this->size() (which is 14)
```
I thought this might be because of the default now in tracking geo is the no-cal geom.
So I added 
```
from LDMX.Tracking.geo import TrackersTrackingGeometryProvider as trackgeo
trackgeo.get_instance().setDetector('ldmx-det-v14-8gev')
```
to the 
https://github.com/LDMX-Software/ldmx-sw/blob/trunk/.github/validation_samples/ecal_pn/config.py
and ran that. It leads to the same exception.

This could be connected to the loss of hits in the tagger, given that the 14 sounds like the number of tagger layers. OTOH I dont know what the 16 is coming from. Anyway, I confirm that the reco.py works out of the box, but we should make sure it works with any geometry (that contains the trackers)

2024-09-15 19:06 UTC, tvami commented
Nvm, I found the source of it, it's the fact that `measurement_collection` has to be passed in the config, so adding
```
recoil_dqm.measurement_collection=digiRecoil.out_collection
```
fixes it. But this means the CI fails with the current config, so @bloodyyugo can you please propagate the changes in the `reco.py` to `.github/validation_samples/ecal_pn/config.py` as well? Thanks!

2024-09-16 14:19 UTC, tvami approved these changes
The only thing left is the CI config change, but we could also do that in a next PR.

2024-09-16 16:58 UTC, EBerzin approved these changes

2024-09-16 21:48 UTC, merged