Hcal tot digitization
LDMXAnalysis/ldmx-sw pull request #1475
Opened 2024-09-25 21:53 UTC by vrm7fj

I am updating _ldmx-sw_, with implemented Hcal TOT digitization.

### What are the issues that this addresses?

## Check List
- [ ] I successfully compiled _ldmx-sw_ with my developments
- [ ] I ran my developments and the following shows that they are successful.

2024-09-26 13:50 UTC, tomeichlersmith requested changes
Thank you for getting this started!

Generally, I would like to see some more detailed explanation on what you've done and then some plots showing that your developments are doing what is intended. Additionally, you have edited HgcrcoEmulator which is also used within the Ecal digitiziation pipeline. Have you confirmed that these edits do not change that pipeline at all?

(Side note: remove the `.DS_Store` files from the branch (using `git rm`). These are not related to the software and just tells me that you are on MacOS!)

2024-10-10 17:29 UTC, vrm7fj commented
**New Class 'PulseRecord':**

This class is intended solely for plotting purposes and should not interfere with the existing workflow. The PulseRecord(double volts, int adc, int tot) function temporarily stores the digitized pulses when the HgcrocEmulator is called by either the Hcal or Ecal pipelines and is cleared each time the emulator is invoked. If the pulse is digitized using ADC, the TOT value is set to zero, and vice versa.

To my understanding, the HgcrocEmulator cannot be called by the Ecal and Hcal pipelines at the exact same time. Therefore, when the getter for PulseRecord is called within the HcalDigiProducer, it will only retrieve the digitized information corresponding to the pulses sent for digitization at that moment. If this understanding is incorrect, the class may only be suitable for studying the back Hcal.

**HgcrocEmulator**

HgcrocEmulator.h has been amended with a mutable vector ‘pulseRecord_’ and a getter to access ‘pulseRecord_’ to store and access digitizations.

Originally, the TOT digitization for an incoming pulse was set by comparing the voltage (vpeak) of the hit, calculated using the pulse function at the time of the hit that comes with the pulse. However, in ADC digitization, the voltage (bxvolts) is calculated using iADC and the clock cycle. There is a slight difference between the two voltage values. See the following debug print.

<img width="748" alt="Screenshot 2024-09-26 at 2 15 34 PM" src="https://github.com/user-attachments/assets/63f0fd94-3e7e-4f0a-acb9-dcd5b7fd60b8">

If we used the original setting:

if (vpeak > totThreshold) {
    startTOT = true;
}

ADC and TOT digitizations look like this. Note that the ADC digitization does not reach up to 1024 counts here.

![ADCTOT2](https://github.com/user-attachments/assets/3d7ab84d-6923-43b1-a3b1-bc107cde9af7)

Instead, if we modify the code as follows, the complete ADC range is utilized in the digitization:

         if (bxvolts > totThreshold){
        /startTOT = true;
        }
        
![ADCTOT](https://github.com/user-attachments/assets/88626bc4-7261-49b3-8168-afb1e71f3d2e)

In this branch, the ‘bxvolts > totThreshold’ condition is currently used.

**HcalDigiProducer** 

Once each section in HcalDigiProducer sends pulses to HgcrocEmulator, they are accessed through the getter and temporarily stored in the vector ‘DigiToPlot’, which is cleared for each ‘hitsByID’ in the loop. At the end of each section, the recorded digitized info is written into a text file following the format [Voltage ADC TOT]. The plots I showed above were generated using that text file.

**hcal_hardcoded_conditions.py  and proposed TOT reconstruction**

Please see the following presentation to understand how changes were made to hcal_hardcoded_conditions and how TOT reconstruction can be implemented.

[LDMX_HCAL.pdf](https://github.com/user-attachments/files/17331780/LDMX_HCAL.pdf)

**Discussion**

Before the implementation of TOT digitization, the histogram of Hcal reconstructed energy was piling up towards the last bins. However, after the implementation, we now observe a smoothed decay in the reconstructed energy. Please note that the appropriate parameters for reconstruction have not yet been configured.

![Image 10-10-24 at 1 25 PM](https://github.com/user-attachments/assets/1aa91331-5466-49c9-9c31-43faaae94cef)

2024-10-25 16:01 UTC, tomeichlersmith requested changes
Thank you for the extra detail. I agree that the new `PulseRecord` class would not be affecting the emulation. The HgcrocEmulator not only is called at separate times but the Ecal and Hcal subsystems have their own _copies_ of the class so they will not interfere. My concern about how this affects the Ecal emulation is from the change in the value used to determine if a specific pulse is above the tot threshold or not. I've highlighted the specific code below. This change is well motivated, I just want to understand the downstream effects.

Besides more specific comments below, my other requests are to remove the `.DS_Store` files that are not interesting for us and write some more documentation into the `PulseRecord` header file. You've already written a nice summary in your comment above so that is a good place to start.

2024-10-25 16:01 UTC, tomeichlersmith commented on Hcal/src/Hcal/HcalDigiProducer.cxx
> +      dataFile.close();
This chunk of code (and the others like it) is incredibly helpful for you the developer when tuning the digitization parameters; however, most people running this producer will not be tuning the parameters and creating an extra txt file would at best be confusing and at worst cause extra issues.

My request here is to put these code blocks behind a configuration parameter such that the user can choose whether to save the digitization information. Maybe a `digi_emulation_file` parameter that is the file to save the information to? (e.g. it could be `"Voltage_ADC_TOT.txt"`) and when it is empty, nothing is saved.

2024-10-25 16:01 UTC, tomeichlersmith commented on Hcal/src/Hcal/HcalDigiProducer.cxx
> +        }
One of the code blocks that could be skipped if the user doesn't want to save the digi emulation detailed information.

2024-10-25 16:01 UTC, tomeichlersmith commented on Hcal/src/Hcal/HcalDigiProducer.cxx
> +
One of the code blocks that could be skipped if the user doesn't want to save the digi emulation detailed information.

2024-10-25 16:01 UTC, tomeichlersmith commented on Hcal/src/Hcal/HcalDigiProducer.cxx
> +        dataFile.close();
One of the code blocks that could be skipped if the user doesn't want to save the digi emulation detailed information.

2024-10-25 16:01 UTC, tomeichlersmith commented on Tools/src/Tools/HgcrocEmulator.cxx
> +      if (bxvolts > totThreshold) {
This is the part that I am worried about effecting the ECal digi emulation as well. This is a substantial change and could affect things there and, while the change is well motivated, I would like to understand what the results are.

2024-10-25 16:01 UTC, tomeichlersmith commented on Tools/src/Tools/HgcrocEmulator.cxx
> +
You don't need the for loop. It will exit on the first entry in the for loop anyways.

```suggestion
      return true;  // always readout
```

2025-01-17 17:33 UTC, tomeichlersmith commented on Hcal/src/Hcal/HcalDigiProducer.cxx
>  >>>>>>> trunk
:warning: conflict leftovers :warning:

2025-04-09 05:48 UTC, tvami commented
@vrm7fj @cmantill what's the status of this? (There are new conflicts)

2025-07-21 15:36 UTC, tvami commented
@cmantill should we close this PR for the time being, until you have somebody to take over? Or maybe @erik-wallin could help in with this development?

2025-07-22 16:20 UTC, erik-wallin commented
#1740 mostly achieves the same goals as this PR, apart from updating the default HGCROC emulator conditions. I'm currently producing MC samples for the testbeam analysis and working on tuning the conditions to match the real data, and they don't quite match the values here. I think it makes sense to use numbers that reflect what we saw at the TB, rather than to pick numbers from the data sheet.

The larger project here is actually using TOT in the reconstruction. In the TB MC samples the transition between the ADC region and TOT region looks quite good: 
<img width="1253" height="643" alt="image" src="https://github.com/user-attachments/assets/3c1434ee-961d-45e3-8179-a12b9c33af6d" />
So I think it will be quite easy to update HCalRecHitProducer to make use of TOT. I probably won't do that in this particular PR though

2025-07-22 18:01 UTC, cmantill commented
I think that most the work to use TOT in the reconstruction was done in the changes to the hcal reco conditions in this PR. So we can close this PR but we should open an issue to address this. I hope Erik can do this (I can help guide!) given that #1740 was merged already.

2025-07-23 15:36 UTC, tvami commented
> So we can close this PR but we should open an issue to address this. 

@cmantill @erik-wallin could one of you make that issue?

2025-07-29 23:29 UTC, tvami commented
OK I made the issue: https://github.com/LDMX-Software/ldmx-sw/issues/1787

Please feel free to edit it!

2025-07-29 23:29 UTC, closed without merging