Wketchum/genie generator hep mc3 refactor
LDMXAnalysis/ldmx-sw pull request #1488
Opened 2024-10-16 12:37 UTC by wesketchum

I am updating _ldmx-sw_, here are the details.

### What are the issues that this addresses?
This PR enables GENIE simulation that include the following:

- A HepMC3GenEvent object to add to the LDMX event bus, inheriting from the HepMC3::GenEvent.
- A EventWeights object to add to the LDMX event bus, for use in event reweighting studies. 
- A GenieGenerator generator that interfaces with the GENIE neutrino generator to run lepton scattering models. Currently the generator is limited to starting interactions at the target. It uses a HepMC3GenEvent as an interface to the event bus.
- A GenieReweightProducer that can run GENIE's Reweight functionality, to reweight events based on turns of systematic knobs. It reads in HepMC3GenEvent recrods, recreates the GENIE internal event record based on that, and then runs reweighting.
- A GenieTruthDQM module that extracts truth GENIE interaction information from the HepMC3GenEvent metadata, and stores it in a flat tree.

## Check List
(note, this requires use of the updated docker image described by this PR: https://github.com/LDMX-Software/docker/pull/105)

- [x] I successfully compiled _ldmx-sw_ with my developments
- [x] I ran my developments and the following shows that they are successful.

An example ldmxsw config is here: https://github.com/wesketchum/LDMX_eN_GENIE/blob/main/ldmxsw_configs/genie_sim.py. From the output of that, one can look at the `genie_truth` tree from the DQM. Attached is a plot of the initial and final lepton energy for a 4 GeV run. 
![lepton_energy_example](https://github.com/user-attachments/assets/15d44cab-67a5-4a9e-9d45-39ac585bb5f7)

Additionally, to see the event reweighting working, here is a screenshot of some screen debug outputs that show weights applied per event.
![Screenshot 2024-10-16 at 14 26 29](https://github.com/user-attachments/assets/26397151-9d1c-41e9-8a44-b6020637da9d)

2025-05-19 15:50 UTC, tomeichlersmith requested changes
As a first pass, I just have some big comments
- Please review the [coding rules](https://ldmx-software.github.io/developing/coding-rules.html), we solidified the format of variable names and such which you should apply here.
- Is `ldmx::HepMC3GenEvent` necessary? If you just need helper functions, I would prefer you to write those helper function somewhere else rather than derive a new event data type.
- Instead of using `if (verbosity ...)` checks, please use `ldmx_log`. I know we haven't transitioned other parts of SimCore to the logging system, but I would really like to avoid adding new code using the old method. It looks like your verbosity of `1` corresponds to the `debug` level.
- Does this compile with ldmx/dev:4.2.2? I just want to update the compatibility table if it doesn't.

2025-05-23 14:13 UTC, wesketchum commented
Working on this...

On `ldmx::HepMC3GenEvent`, I added i because I thought it was necessary for the `Print()` and `Clear()` functions were needed for things put onto the event bus. If that's not the case/there's a way around that, then I'd be very happy to get rid of it, and then yes, can have a helper class that is separate for anything that may be needed.

2025-05-23 14:41 UTC, tomeichlersmith commented
You're correct, the `Print` and `Clear` functions are still necessary so I withdraw that comment.

2025-05-26 15:40 UTC, wesketchum commented
OK, so:

- Reviewed code style and tried to comply. format-cpp run.
- Ran asan/ubsan and LTO builds. Minor changes after that.
- Merged with trunk (resolving conflicts on `DQM/python/dqm.py`)

Think we are ready for a re-review.

2025-05-27 15:34 UTC, tomeichlersmith reviewed
More comments, apologies that this might take several rounds given how big this PR is. If you are out of time and need to just get this merged, let me know and I can prioritize that.

2025-05-27 15:34 UTC, tomeichlersmith commented on SimCore/src/SimCore/Reweight/GenieReweightProducer.cxx
> +  delete genie_rw_;
Have you tried just using plain objects instead of pointers? Or if you need pointers, maybe `std::unique_ptr` so that the `delete` happens no-matter what?

2025-05-27 15:34 UTC, tomeichlersmith commented on SimCore/src/SimCore/Reweight/GenieReweightProducer.cxx
> +  n_weights_ = (size_t)(ps.getParameter<int>("n_weights"));
I have a vendetta against C-style casts[^1]

[^1]: reason: https://www.youtube.com/watch?v=SmlLdd1Q2V8

```suggestion
  n_weights_ = static_cast<size_t>(ps.getParameter<int>("n_weights"));
```

2025-05-27 15:34 UTC, tomeichlersmith commented on SimCore/src/SimCore/Reweight/GenieReweightProducer.cxx
> +  hepmc3CollName_ = ps.getParameter<std::string>("hepmc3CollName");
Fun fact, in a Framework update a while ago, I changed `Parameters` to have a shorter accessor function.

Not really necessary, just using this as a soap-box to try to advertise this update a bit more.

```suggestion
  hepmc3CollName_ = ps.get<std::string>("hepmc3CollName");
```

2025-05-27 15:34 UTC, tomeichlersmith commented on SimCore/src/SimCore/Reweight/GenieReweightProducer.cxx
> +  genie_rw_->AdoptWghtCalc("hadro_intranuke", new genie::rew::GReWeightINuke);
Does `genie_rw_` own these objects you created with `new`? (will it `delete` them?)

2025-05-27 15:34 UTC, tomeichlersmith commented on SimCore/src/SimCore/Reweight/GenieReweightProducer.cxx
> +  genie_rw_ = new genie::rew::GReWeight;
If this object doesn't have a reset-in-place option making it possible to use a non-pointer type, you can still use `std::unique_ptr` with the `reset` function.
```suggestion
// if genie_rw_ is a std::unique_ptr<genie::rew::GReWeight>
genie_rw_.reset(new genie::rew::GReWeight);
```

2025-05-27 15:34 UTC, tomeichlersmith commented on cmake/BuildMacros.cmake
> +macro(setup_genie_target)
I would like to update this CMake to be
- formatted so its easier to see function definition boundaries
- target-based so we can just use `target_link_libraries` instead of having to `include_directories` and `${GENIE_LIBS}` in the `SimCore/CMakeLists.txt`
I can figure this out if you are unfamiliar with CMake and don't have the time to learn.

2025-05-27 15:34 UTC, tomeichlersmith commented on SimCore/src/SimCore/Simulator.cxx
> +  event.add("SimHepMC3Events", hepmc3_events);
I'm curious on if we could avoid including this collection when not running the GENIE generator. Right now, this looks like we will be carrying around an empty branch with all of our other run configurations and I think that is a waste of space and potentially confusing. Could this `event.add` call be skipped if `hepmc3_events` is empty?

2025-05-27 16:11 UTC, tvami reviewed
I had a few comments about doubles, logging system, and some cosmetics

2025-05-27 16:11 UTC, tvami commented on SimCore/include/SimCore/Generators/GenieGenerator.h
> +  double xsec_total_;
I think these could be `float`-s, or do you see the need for `double` precision?

2025-05-27 16:11 UTC, tvami commented on SimCore/include/SimCore/Event/EventWeights.h
> +#define SIM_CORE_EventWeights_H
```suggestion
#ifndef SIMCORE_EventWeights_H
#define SIMCORE_EventWeights_H
```
this is how you did it in other cases too

2025-05-27 16:11 UTC, tvami commented on SimCore/include/SimCore/Reweight/GenieReweightProducer.h
> +  virtual ~GenieReweightProducer();
```suggestion
  virtual ~GenieReweightProducer() = default;
```

2025-05-27 16:11 UTC, tvami commented on SimCore/python/generators.py
> +                     energy=4.0,
Should this be 8?
```suggestion
                     energy=8.0,
```

2025-05-27 16:11 UTC, tvami commented on SimCore/python/generators.py
> +                     target_thickness = 0.3504,
what unit is this in? (my comment is more like please add what unit it is in the Attributes above)
Is this Ti specific?

2025-05-27 16:11 UTC, tvami commented on SimCore/python/genie_reweight.py
> +        self.verbosity = 0
we should not have this, but rather use the ldmx logging system

2025-05-27 16:11 UTC, tvami commented on SimCore/src/SimCore/Generators/GenieGenerator.cxx
> +    ldmx_log(debug) << "\tAdding particle " << p->Pdg() << " with status "
I think this might be under `trace`
https://ldmx-software.github.io/developing/Logging.html

2025-05-27 16:11 UTC, tvami commented on SimCore/src/SimCore/Reweight/GenieReweightProducer.cxx
> +                << ")" << std::endl;
Please move these into the logging system

2025-05-30 04:53 UTC, wesketchum commented on SimCore/src/SimCore/Reweight/GenieReweightProducer.cxx
> +  delete genie_rw_;
Was following examples from within GENIE, which (criminally) don't use smart ptrs ... so yes, good idea. Implemented (and I hope correctly).

2025-05-30 04:56 UTC, wesketchum commented on SimCore/src/SimCore/Reweight/GenieReweightProducer.cxx
> +  n_weights_ = (size_t)(ps.getParameter<int>("n_weights"));
OK, done. I'll take the opportunity to advocate for an unsigned int on getParameter if it's not there? (I assume I tried this and it did not work, and assume you'd tell me to do that rather than cast if it did.)

2025-05-30 04:57 UTC, wesketchum commented on SimCore/src/SimCore/Reweight/GenieReweightProducer.cxx
> +  hepmc3CollName_ = ps.getParameter<std::string>("hepmc3CollName");
Updated!

2025-05-30 04:58 UTC, wesketchum commented on SimCore/src/SimCore/Reweight/GenieReweightProducer.cxx
> +  genie_rw_->AdoptWghtCalc("hadro_intranuke", new genie::rew::GReWeightINuke);
Yes (or at least it claims to own), and yes, it does delete them.

2025-05-30 04:59 UTC, wesketchum commented on SimCore/src/SimCore/Reweight/GenieReweightProducer.cxx
> +  genie_rw_ = new genie::rew::GReWeight;
Just calling a make_unique here now, so should be better.

2025-05-30 04:59 UTC, wesketchum commented on cmake/BuildMacros.cmake
> +macro(setup_genie_target)
I would appreciate your help here. I _should_ take the time to learn, but the chances of that happening quickly are not too high.

2025-05-30 05:05 UTC, wesketchum commented on SimCore/src/SimCore/Simulator.cxx
> +  event.add("SimHepMC3Events", hepmc3_events);
Yes, that's a very valid point. I don't think it should be a problem to skip the add if `hepmc3_events.size()==0`. Changed to that.

2025-05-30 05:09 UTC, wesketchum commented on SimCore/include/SimCore/Generators/GenieGenerator.h
> +  double xsec_total_;
Likely right. Updated.

2025-05-30 05:12 UTC, wesketchum commented on SimCore/include/SimCore/Event/EventWeights.h
> +#define SIM_CORE_EventWeights_H
Thanks. Fixed.

2025-05-30 05:12 UTC, wesketchum commented on SimCore/include/SimCore/Reweight/GenieReweightProducer.h
> +  virtual ~GenieReweightProducer();
Right -- the comment was wrong before actually, but now using unique ptrs, I can use the default constructor again. Done.

2025-05-30 05:14 UTC, wesketchum commented on SimCore/python/generators.py
> +                     energy=4.0,
yes ...

2025-05-30 05:15 UTC, wesketchum commented on SimCore/python/generators.py
> +                     target_thickness = 0.3504,
mm (comment added).

2025-05-30 05:21 UTC, wesketchum commented on SimCore/python/genie_reweight.py
> +        self.verbosity = 0
OK, so ... fair general point, but this is actually controlled a call to a `Print()` call on event objects. How would that be done via the logging system?

2025-05-30 05:22 UTC, wesketchum commented on SimCore/src/SimCore/Generators/GenieGenerator.cxx
> +    ldmx_log(debug) << "\tAdding particle " << p->Pdg() << " with status "
It's not so many particles (O(10) per event), as it's only the 'final state' particles passed from GENIE to G4, and, in 'debugging', seeing the particles produced and passed to G4 is very useful, so I prefer to keep as is.

2025-05-30 05:22 UTC, wesketchum commented on SimCore/src/SimCore/Reweight/GenieReweightProducer.cxx
> +                << ")" << std::endl;
This one moved, yes.

2025-05-30 05:29 UTC, wesketchum commented on SimCore/include/SimCore/Generators/GenieGenerator.h
> +  double xsec_total_;
Well, actually, as get<float> doesn't appear to work, and there's not an easy(that I know of) casting of vector<double> to vector<float>, I've left the vector<double> ones that are read in by config. The size here is not a problem, so I hope convenience can win out.

2025-05-30 05:43 UTC, wesketchum commented
OK, huge thanks to @tomeichlersmith and @tvami for the comments. I've implemented what I can and left comments.

Two things with respect to logging:

(1) What should be done for a conditional print that is calling an event object's `Print()` call, like so:
```
if (verbosity_ >= 1) ev_weights.Print();
```
Should event objects `Print()` calls also use the logging system? (Seems ... no.) I think maintaining a verbosity flag here may be warranted.

(2) I had some messages being printed in the destructor of GenieGenerator, in order to print out some 'end of run' information, summarizing total events generated, xsecs, etc. When these were couts, no problem, but making them into `ldmx_log(info)` messages gives me an error at the end of processing:
```
---- LDMXSW: Event processing complete  --------
terminate called after throwing an instance of 'boost::wrapexcept<boost::exception_detail::error_info_injector<boost::log::v2_mt_posix::system_error> >'
  what():  Failed to set TLS value: Invalid argument [system:22]
 ```
pointing back to the GenieGenerator destructor.

Arguably the destructor is a bad place for this, but I did not know where else. Is there a way to print such 'summary' stats in the Simulator? If not, I may look into adding it ... and may in the meantime request an exemption to use a cout for now.

2025-05-30 13:53 UTC, tomeichlersmith commented on SimCore/src/SimCore/Reweight/GenieReweightProducer.cxx
> +  n_weights_ = (size_t)(ps.getParameter<int>("n_weights"));
We are converting from Python types and so long-story-short we will not support an unsigned int from getParameter. The supported types are
- `list` (1D and 2D) to `std::vector` of type in the first element
- `object` and `dict` to `Parameters` holding their members
- `str` to `std::string`
- `int` to `int`
- `float` to `double`
- `bool` to `bool`

https://github.com/LDMX-Software/ldmx-sw/blob/e3c9d41b105ff88451ebcbad77dbce7ba466830e/Framework/src/Framework/Configure/Python.cxx#L146C1-L152C50

2025-05-30 13:57 UTC, tomeichlersmith commented on SimCore/include/SimCore/Generators/GenieGenerator.h
> +  double xsec_total_;
Parameters extracted from Python `float` are the size of C++ `double` so we need to initially extract them to `double`. I don't want to support quietly extracting a Python `float` to a C++ `float` for the same reason I don't want to support a Python `int` to a C++ `unsigned int`. I support @wesketchum in keeping the **parameters** `double` as long as the objects that end up in the output event file are `float` in order to save space.

2025-05-30 14:11 UTC, tomeichlersmith commented
1. Please refactor the `Print`. You should use a `operator<<(std::ostream&, ldmx::EventWeight&)` so that you can send an event weight to the logging stream and then `Print` just becomes `{ std::cout << *this; }`. See `Recon/Event/HgcrocTrigDigi` for an example. Other event classes don't do this and we just manually construct a logging message from their accessors (which may be what we have to do if this streaming `operator<<` thing doesn't work).
2. You are correct this is due to the logging system. The Boost exceptions are from Boost logging already being "closed" before you try to send messages to it. We do not have a callback in PrimaryGenerators for end-of-run summary statistics. Personally, I'm okay leaving it with `cout` **without the verbosity flag**. This will be a helpful reminder to add a callback to PrimaryGenerators if we want to insert this into the logging system in order to quiet it.

2025-05-30 15:52 UTC, tvami commented on SimCore/src/SimCore/Generators/GenieGenerator.cxx
> +    ldmx_log(debug) << "\tAdding particle " << p->Pdg() << " with status "
Ok sounds good!

2025-05-30 15:53 UTC, tvami commented on SimCore/python/genie_reweight.py
> +        self.verbosity = 0
I agree with Tom's suggestion below 
https://github.com/LDMX-Software/ldmx-sw/pull/1488#issuecomment-2922509201
to have the Print as cout, but to not have the verbosity flag.

2025-05-30 15:55 UTC, tvami commented on SimCore/include/SimCore/Generators/GenieGenerator.h
> +  double xsec_total_;
OK indeed what matters is the format of what's in the output event file

2025-05-30 18:21 UTC, EinarElen commented on SimCore/include/SimCore/Generators/GenieGenerator.h
> +  double xsec_total_;
Regarding this, I would even argue that we should prioritize using double precision for anything that doesn't end up in the event records. Floating point issues are so much easier to run into with single precision and are a nightmare to deal with

2025-05-30 18:48 UTC, tvami commented on SimCore/include/SimCore/Generators/GenieGenerator.h
> +  double xsec_total_;
Maybe we should make this a dedicated issue @EinarElen because I'm the side of having `float`-s where `float`-s are enough, and having `double`-s only where they are needed.

2025-05-30 20:46 UTC, tomeichlersmith commented on cmake/BuildMacros.cmake
> +macro(setup_genie_target)
I wasn't able to figure out the target-based approach so I just formatted it.

2025-06-12 15:56 UTC, tomeichlersmith requested changes
Just some leftover cleanup, but its looking good :)

2025-06-12 15:56 UTC, tomeichlersmith commented on SimCore/include/SimCore/Event/HepMC3GenEvent.h
> +  virtual ~HepMC3GenEvent() {}
```suggestion
  virtual ~HepMC3GenEvent() = default;
```

2025-06-12 15:56 UTC, tomeichlersmith commented on SimCore/include/SimCore/Reweight/GenieReweightProducer.h
> +
```suggestion
```

2025-06-12 15:56 UTC, tomeichlersmith commented on SimCore/python/generators.py
> +        Verbosity flag for this generator
```suggestion
```

2025-06-12 15:56 UTC, tomeichlersmith commented on SimCore/include/SimCore/Generators/GenieGenerator.h
> +   *  verbosity : > 1 means print configuration
```suggestion
```

2025-06-12 16:10 UTC, tvami commented on SimCore/src/SimCore/Generators/GenieGenerator.cxx
> +  std::cout << "--- GENIE Generation Summary BEGIN ---" << std::endl;
I'm confused here: I thought these could become part of the logging system, is that not right?

2025-06-12 16:20 UTC, tvami requested changes
I also found some important typos

2025-06-12 16:20 UTC, tvami commented on DQM/src/DQM/GenieTruthDQM.cxx
> +    ntuple_.setVar<int>("rescatter_code", scattering_type_ptr->value());
this is a copy paste error
```suggestion
    ntuple_.setVar<int>("rescatter_code", rescatter_code_ptr->value());
```

2025-06-12 16:20 UTC, tvami commented on DQM/src/DQM/GenieTruthDQM.cxx
> +  if (hqrksea_ptr) ntuple_.setVar<int>("hqrk_sea", hqrkpdg_ptr->value());
here too
```suggestion
  if (hqrksea_ptr) ntuple_.setVar<int>("hqrk_sea", hqrksea_ptr->value());
```

2025-06-12 16:20 UTC, tvami commented on SimCore/src/SimCore/Event/EventWeights.cxx
> +  }
does this not need to return o?
```
return o;
```

2025-06-12 16:34 UTC, tomeichlersmith commented on SimCore/src/SimCore/Generators/GenieGenerator.cxx
> +  std::cout << "--- GENIE Generation Summary BEGIN ---" << std::endl;
The logging system is already closed by the time the generator desctructor is called.

https://github.com/LDMX-Software/ldmx-sw/pull/1488#issuecomment-2921291585

I said it was okay to leave these to `cout` until we add a callback to the PrimaryGenerator class for end-of-run activities.

2025-06-12 16:44 UTC, tvami commented on SimCore/src/SimCore/Generators/GenieGenerator.cxx
> +  std::cout << "--- GENIE Generation Summary BEGIN ---" << std::endl;
ok thanks!

2025-06-20 13:52 UTC, wesketchum commented on SimCore/include/SimCore/Event/HepMC3GenEvent.h
> +  virtual ~HepMC3GenEvent() {}
done

2025-06-20 13:53 UTC, wesketchum commented on SimCore/include/SimCore/Reweight/GenieReweightProducer.h
> +
done

2025-06-20 13:53 UTC, wesketchum commented on SimCore/python/generators.py
> +        Verbosity flag for this generator
done.

2025-06-20 13:53 UTC, wesketchum commented on SimCore/include/SimCore/Generators/GenieGenerator.h
> +   *  verbosity : > 1 means print configuration
done

2025-06-20 13:53 UTC, wesketchum commented on DQM/src/DQM/GenieTruthDQM.cxx
> +    ntuple_.setVar<int>("rescatter_code", scattering_type_ptr->value());
good catch! thank you!

2025-06-20 13:53 UTC, wesketchum commented on DQM/src/DQM/GenieTruthDQM.cxx
> +  if (hqrksea_ptr) ntuple_.setVar<int>("hqrk_sea", hqrkpdg_ptr->value());
another good catch. thank you!

2025-06-20 13:53 UTC, wesketchum commented on SimCore/src/SimCore/Event/EventWeights.cxx
> +  }
yes! done.

2025-06-20 13:58 UTC, tvami approved these changes
thanks a lot Wes! all good from my side!

2025-06-20 14:15 UTC, tomeichlersmith approved these changes
Looks good to me too :) thank you

2025-06-20 14:42 UTC, tvami commented
ups ASAN failed
https://github.com/LDMX-Software/ldmx-sw/actions/runs/15781041353/job/44486508221?pr=1488

2025-06-20 14:46 UTC, tvami commented
Do I understand the msg that the issue is that `UserEventInformation` doesnt have a `.cxx` file?

2025-06-20 16:01 UTC, tomeichlersmith commented
The `UserEventInformation` does have a implementation file. That error is saying that the `simcore::UserEventInformation` (i.e. the constructor) is not defined for that library. For us, this means the library where `UserEventInformation` is defined (SimCore) has not been loaded when the library where it is being used (SimCore_Generators) is being loaded.
I'm not sure how to solve this problem or why its showing up now, I guess this is the first generator using `UserEventInformation` directly.

2025-06-21 07:15 UTC, wesketchum commented
OK, I've managed to get this to run at least one of the failing ASAN-compiled validation checks. I imagine the rest will follow ...

From my understanding, I think there are two options here:

- We make UserEventInformation and other similar ones (UserTrackInformation, UserRegionInformation, and UserPrimaryParticleInformation) header only. 
- We move them to some compiled library (like G4User), and then adjust links and dependencies throughout the code.

I've done the second option in local code, and that appears to be working (well, outside of many warnings on memory leaks, which I think are unrelated). I've not tried the first option...I suspect it would work, and it may be 'cleaner' in the amount of code that needs to be changed. But I don't have strong preferences there.

Assuming those are our options, I'd recommend we decide what we would like to do, make a separate PR that does that reorganization, test that it works for everything in trunk as-is, and then I can pull those changes into my branch for testing with the GenieGenerator.

2025-06-21 13:55 UTC, tomeichlersmith commented
I agree the second option is best - started a branch: https://github.com/LDMX-Software/ldmx-sw/tree/re-ord-simcore-libs

2025-06-24 12:05 UTC, wesketchum commented
OK, with #1736 now merged into this branch, the build is working and I can run a simulation change. I've pushed up the minor updates needed here.

2025-06-24 16:54 UTC, tomeichlersmith approved these changes
Just re-approving because I am ready to merge now.

2025-06-25 02:06 UTC, merged