Provision of EcalTrigPrimDigis
LDMXAnalysis/ldmx-sw pull request #916
Opened 2020-09-24 21:13 UTC by jmmans

Builds on iss895 and other pull requests to bring in the ability to create trigger primitives for Ecal.

Example python file (hidden as a txt file for github)
[sim_and_reco_example_py.txt](https://github.com/LDMX-Software/ldmx-sw/files/5279207/sim_and_reco_example_py.txt)

2020-09-25 19:11 UTC, tomeichlersmith commented
Depends on PR #914 for updates to the conditions system.

2020-09-25 19:19 UTC, tomeichlersmith commented
## Related Submodule PRs
- https://github.com/LDMX-Software/Ecal/pull/17
- https://github.com/LDMX-Software/SimCore/pull/29
- https://github.com/LDMX-Software/Framework/pull/26

2020-09-28 15:36 UTC, tomeichlersmith commented
## Still To-Do
- [ ] Integrate the `HgcrocTriggerCalculations` into the `HgcrocEmulator` so that it is available for Hcal and the emulation of the chip is done in one place
- [ ] Allow for passing _separate conditions tables_ for the trigger calculations and the reconstruction. This is important becuase in the future, we can change the recon conditions (e.g. the recon pedestals) but can't change the conditions that the data was gathered under.
- [ ] Cleanup and documentation, specifically focused on announcing this necessary change to any configuration that wants to use the ecal digi pipeline: The user will need to import a set of conditions for the ecal digi pipeline to function properly. Again, this is important because the user can choose different conditions to import from.

2020-09-28 16:09 UTC, jmmans commented
Dear Tom,

I don't understand point 2 -- this is already the case, so why does it 
appear here?  The action would be to add the use of condition tables for 
reconstruction, but that shouldn't be part of this pull request.

Jeremy

On 9/28/20 10:36 AM, Tom Eichlersmith wrote:
> 
>     Still To-Do
> 
>   * Integrate the |HgcrocTriggerCalculations| into the |HgcrocEmulator|
>     so that it is available for Hcal and the emulation of the chip is
>     done in one place
>   * Allow for passing /separate conditions tables/ for the trigger
>     calculations and the reconstruction. This is important becuase in
>     the future, we can change the recon conditions (e.g. the recon
>     pedestals) but can't change the conditions that the data was
>     gathered under.
>   * Cleanup and documentation, specifically focused on announcing this
>     necessary change to any configuration that wants to use the ecal
>     digi pipeline: The user will need to import a set of conditions for
>     the ecal digi pipeline to function properly. Again, this is
>     important because the user can choose different conditions to import
>     from.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/LDMX-Software/ldmx-sw/pull/916#issuecomment-700099499>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ABFUPYAPQDAES244QRZW4DDSICURDANCNFSM4RYY6FEQ>.
>

2020-09-28 16:10 UTC, tomeichlersmith commented
Good point, I was just copying down my thoughts to make sure I don't forget anything. I will mark that as "done".

2020-10-12 19:55 UTC, tomeichlersmith approved these changes
Looks good to me. Was able to merge the sub-module Ecal PR and update the ref here, so we are good to go.

2020-10-13 20:54 UTC, omar-moreno commented on Event/include/Event/HgcrocTrigDigi.h
> +  virtual ~HgcrocTrigDigi();
If this does nothing, then might as well set it equal to default 
`virtual ~HgcrocTrigDigi() = default;`

you can then remove the definition from the src file.

2020-10-13 20:55 UTC, omar-moreno commented on Event/include/Event/HgcrocTrigDigi.h
> +  bool operator<(const HgcrocTrigDigi &d) {
I suggest making the variable name a bit clearer i.e. d --> digi

2020-10-13 22:23 UTC, omar-moreno requested changes

2020-10-13 22:25 UTC, omar-moreno commented
Looks fine overall, but would be useful to have some documentation on how the trigger primitive bits are being set.

2020-10-15 19:02 UTC, omar-moreno approved these changes

2020-10-15 20:48 UTC, merged